# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
#import:
#  - /path/to/alacritty.yml

window:
  title: Alacritty Terminal
  dynamic_title: false
  opacity: 0.75
shell:
  program: /usr/bin/zsh
title: Alacritty
dynamic_title: false
history: 10000
